
version: 2

sources:
  - name: demo_data
    database: demo_db
    schema: public
    tables:
      - name: orders
        columns:
          - name: ord_id
            tests:
              - unique:
                  severity: Warn
                  store_failures: False
              - not_null:
                  severity: warn
                  store_failures: True

          - name: cust_id
            tests:
              - relationships:
                  to: source('demo_data','customer')
                  field: cust_id
                  store_failures: true
                  severity: Warn
                  
      - name: customer
        columns:
          - name: cust_id
            tests:
              - not_null
              - unique
              - accepted_values:
                  values: [10,11,12,13,14]
  

  - name: Employee_Data
    database: DBTPRACTICE_{{ env_var('DBT_ENVR') }}
    schema: raw
    tables:
      - name: Employee
  - name: Ecommerce
    database: raw_data
    schema: ECOMMERCE
    tables:
      - name: RAW_CUSTOMERS
      - name: RAW_ORDERS


models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: ord_cust_stg
    description: "This model contains customer and thier orders info.."
    columns:
      - name: cust_id
        data_tests:
          - unique
          - not_null
          - accepted_values:
              values: [10,11,12,13,14]
          - relationships:
              to: source("demo_data","customer")
              field: cust_id
              